#!/usr/bin/env bash

_reallymakepkg() {
  local \
    _pkgs=() \
    _arch='https://gitlab.archlinux.org'
  _pkgs=("$@")
  [[ ! -n "${TERMUX_VERSION}"]] && \
    _tmpdir="$(mktemp -d)" && \
    cp \
      -a \
      "$(pwd)"/* \
      "${_tmpdir}" && \
    sed \
      "s/pkgdir/terdir/g" \
      "$(pwd)/PKGBUILD" > \
      "${tmpdir}/PKGBUILD"
  for _pkg in "${_pkgs[@]}"; do
    git \
      clone \
      "${_arch}/archlinux/packaging/packages/${_pkg}"
  done
}

_pkgs=("$@")

[[ ${#} < 1]] &&\
  echo \
    'Usage: aspe [pkgs]

_aspe \
  "${_pkgs[@]}"
