#!/usr/bin/env bash

_reallymakepkg() {
  local \
    _args=()
  _args=(
    "$@")
  [[ -n "${TERMUX_VERSION}" ]] && \
    _tmpdir="$(mktemp -d)" && \
    cp \
      -a \
      "$(pwd)"/* \
      "${_tmpdir}" && \
    sed \
      "s/pkgdir/terdir/g" \
      "$(pwd)/PKGBUILD" > \
      "${_tmpdir}/PKGBUILD"
  cd \
    "${_tmpdir}"
  makepkg \
    "${_args[@]}"
  mv \
    *".pkg."* \
    "${OLDPWD}"
  cd \
    "${OLDPWD}"
}

_args=(
  "$@")

_reallymakepkg \
  "${_args[@]}"
