#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

# System-independent makepkg
_reallymakepkg() {
  local \
    _args=()
  _args=(
    "$@")
  [[ -n "${TERMUX_VERSION}" ]] && \
    _termux_makepkg \
      "${_args[@]}" && \
    return
  makepkg \
    "${_args[@]}"
}

# Set C flags for the termux environment
_termux_flags() {
  if [[ \
    ! " ${LDFLAGS} " =~ \
      '-landroid-shmem -landroid-execinfo' ]] then
    export \
      LDFLAGS="${LDFLAGS} -landroid-shmem -landroid-execinfo"
  fi 
}

# Roughly determine if a package contains a Python package
_is_python_pkg() {
  local \
    _pkgname=() \
    _provides=() \
    _pkg
  _flag=""
  _pkgname=(
    $(source \
        "${_tmpdir}/PKGBUILD" && \
      echo \
        "${pkgname[@]}"))
  for _pkg \
    in "${_pkgname[@]}"; do
    if [[ "${_pkg}" == "python"*"-"* ]]; then
      _flag=true
      break
    fi
  done
  _provides=(
    $(source \
        "${_tmpdir}/PKGBUILD" && \
      echo \
        "${provides[@]}"))
  for _pkg \
    in "${_provides[@]}"; do
    if [[ "${_pkg}" == "python"*"-"* ]]; then
      _flag=true
      break
    fi
  done
}

_is_setuptools_pkg() {
  _flag="$( \
    cat \
      "${_tmpdir}/PKGBUILD" | \
      grep \
        -o \
        'setup.py')"
}

_is_build_pkg() {
  local \
    _makedepends=() \
    _pkg \
  _flag=""
  _makedepends=(
    $(source \
        "${_tmpdir}/PKGBUILD" && \
      echo \
        "${makedepends[@]}"))
  for _pkg \
    in "${_makedepends[@]}"; do
    if [[ "${_pkg}" == "python-build" ]]; then
      _flag=true
      break
    fi
  done
}

_python_quirks() {
  local \
    _build_pattern \
    _flag \
    _setuptools_pattern
  _is_python_pkg
  if [[ "${_flag}" == "true" ]]; then
    echo \
      "INFO: detected as python pkg"
    _is_setuptools_pkg 
    if [[ "${_flag}" != "" ]]; then
      echo \
        "INFO: detected as setuptools pkg"
      _setuptools_pattern="$( \
        cat \
          "${_tmpdir}/PKGBUILD" | \
          grep \
            -o \
            'root=[^ ]*terdir[^ ]*')"
      [[ "${_setuptools_pattern}" != "" ]] && \
	echo \
	  "INFO: reverting terdir to pkgdir in --root option"
        sed \
          -i \
          "s/${_setuptools_pattern}/root=\"\${pkgdir}\"/g" \
          "${_tmpdir}/PKGBUILD"
    fi
    _is_build_pkg
    if [[ "${_flag}" == "true" ]]; then
      echo \
	"INFO: Using / instead of terdir in build module's --destdir"
      _build_pattern="$( \
        cat \
          "${_tmpdir}/PKGBUILD" | \
          grep \
            -o \
            'destdir=[^ ]*terdir[^ ]*')"
      [[ "${_build_pattern}" != "" ]] && \
        sed \
          -i \
          "s%${_setuptools_pattern}%destdir=/%g" \
          "${_tmpdir}/PKGBUILD"
    fi
  fi
}

# Termux makepkg
# $@:makepkg args
_termux_makepkg() {
  local \
    _args=() \
    _pypattern
  _args=(
    "$@")
  _tmpdir="$( \
    mktemp \
      -d)"
  cp \
    -a \
    "$(pwd)"/* \
    "${_tmpdir}"
  sed \
    "s/pkgdir/terdir/g" \
    "$(pwd)/PKGBUILD" > \
    "${_tmpdir}/PKGBUILD"
  _python_quirks
  cd \
    "${_tmpdir}"
  _termux_flags
  cat \
    PKGBUILD
  makepkg \
    "${_args[@]}"
  [[ $? -eq 0 ]] && \
  [[ *".pkg."* != "" ]] && \
    mv \
      *".pkg."* \
      "${OLDPWD}" && \
    rm \
      -rf "${_tmpdir}"
  cd \
    "${OLDPWD}"
}

_args=(
  "$@")

_reallymakepkg \
  "${_args[@]}"
