#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
        "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"

_global_variables() {
  install_date=""
  input_file=""
  output_file=""
  tree_dir=""
  shared_dir=""
  root_dir=""
  file_execuable=""
  color=""
  quiet=""
}

_pkgdir_get() {
  local \
    _pkgdir="${1}"
  realpath \
    "${_pkgdir%${TERMUX_PREFIX}}"
}

# Installs a file in the Android shared
# directory tree and creates a corresponding
# link in the root directory tree.
_termux_install_shared() {
  local \
    _input_file="${1}" \
    _root_dir="${2}" \
    _tree_dir="${3}" \
    _shared_dir="${4}" \
    _output_file="${5}" \
    _file_executable="${6}" \
    _install_dir \
    _real_dir \
    _pkgdir \
    _os \
    _android_sdcard \
    _msg=() \
    _install_opts=() \
    _mode
  if [[ "${quiet}" == "n" ]] then
    _install_opts=+(
      -v
    )
  fi
  _os="$( \
    uname \
      -o)"
  _android_sdcard="/storage/emulated/0"
  install \
    "${_install_opts[@]}" \
    -dm755 \
    "${_root_dir}${_tree_dir}"
  if [[ "${_os}" == "GNU/Linux" ]]; then
    _real_dir="${_tree_dir}"
    _install_dir="${_root_dir}${_real_dir}"
  elif [[ "${_os}" == "Android" ]]; then
    _real_dir="${_android_sdcard}/${_shared_dir}"
    _pkgdir="$( \
      _pkgdir_get \
        "${_root_dir}")"
    _install_dir="${_pkgdir}${_real_dir}"
    ln \
      -s \
      "${_real_dir}/${_output_file}" \
      "${_root_dir}${_tree_dir}/${_output_file}"
  fi
  if [[ "${_file_executable}" == "y" ]]; then
    _mode="755"
  elif [[ "${_file_executable}" == "n" ]]; then
    _mode="644"
  fi
  _install_opts=(
    -Dm"${_mode}"
  )
  install \
    "${_install_opts[@]}" \
    "${_input_file}" \
    "${_install_dir}/${_output_file}"
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "install" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "output" \
    "file" \
    "$(basename \
         "${input_file}")"
  _set_override \
    "file" \
    "executable" \
    "n"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit_code="${1}"
  IFS='' \
    read \
      -r \
      -d '' \
      usage_text << \
        ENDUSAGETEXT || true

Seamlessly install Termux files in Android shared storage area.


usage:

  ${app_name}
    [options]
    <input_file>
    <root_dir>
    <tree_dir>
    <shared_dir>
    (<output_file>)


  arguments:
    input_file            The file to install.
    root_dir              The value of the 'pkgdir'
                          variable in the PKGBUILD.
    tree_dir              The destination path of the 
                          file in the Termux tree at
                          which to place the link.
    shared_dir            The destination path of the
                          file in the Android shared
                          directory.
    output_file           Output file name.


  options:
     -x                   Whether to make the file
                          executable on install.

     -h                   This message.
     -c                   Enable colors
     -v                   Enable verbose output
ENDUSAGETEXT
  printf \
    '%s\n' \
    "${usage_text}"
  exit \
    "${_exit_code}"
}

_display_flags() {
  local \
    _flags=(
      ${1}
    )
  for _flag \
    in "${_flags[@]}"; do
  _msg_info "                              ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration settings"
  _msg_info "       Install date:   ${install_date}"
  _msg_info "         Input file:   ${input_file}"
  _msg_info "     Root directory:   ${root_dir}"
  _msg_info "     Tree directory:   ${tree_dir}"
  _msg_info "   Shared directory:   ${shared_dir}"
  _msg_info "         Executable:   ${file_executable}"
  _msg_info "        Output file:   ${output_file}"
}

_globals
_global_variables

while \
  getopts \
    'xcvh?' \
    arg; do
  case \
    "${arg}" in
    x) override_file_executable="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _usage \
	   1 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( "$#" < 4 )); then
  _set_overrides
  _usage \
    1
fi
input_file="${1}"
root_dir="${2}"
tree_dir="${3}"
shared_dir="${4}"
if (( 4 < "$#" )); then
  output_file="${5}"
fi
_set_overrides
app_opts=(
  "${input_file}"
  "${root_dir}"
  "${tree_dir}"
  "${shared_dir}"
  "${output_file}"
  "${file_executable}"
)
_termux_install_shared \
  "${app_opts[@]}"
