#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
        "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"

_global_variables() {
  install_date=""
  tree_dir=""
  shared_dir=""
  root_dir=""
  color=""
  quiet=""
}

# Installs a file in the Android shared
# directory tree and creates a corresponding
# link in the root directory tree.
_termux_install_shared() {
  local \
    _root_dir="${1}" \
    _tree_dir="${2}" \
    _shared_dir="${3}" \
    _msg=()
  echo \
    "hi"
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "install" \
    "date" \
    "$(_get_date_human)"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit_code="${1}"
  IFS='' \
    read \
      -r \
      -d '' \
      usage_text << \
        ENDUSAGETEXT || true

Seamlessly install Termux files in Android shared storage area.

usage:

  ${app_name}
    [options]
    <root_dir>
    <tree_dir>
    <shared_dir>

  arguments:
    root_dir              The value of the 'pkgdir'
                          variable in the PKGBUILD.
    tree_dir              The destination path of the 
                          file in the Termux tree at
                          which to place the link.
    shared_dir            The destination path of the
                          file in the Android shared
                          directory.

  options:
     -h                   This message.
     -c                   Enable colors
     -v                   Enable verbose output
ENDUSAGETEXT
  printf \
    '%s\n' \
    "${usage_text}"
  exit \
    "${_exit_code}"
}

_display_flags() {
  local \
    _flags=(
      ${1}
    )
  for _flag \
    in "${_flags[@]}"; do
  _msg_info "                              ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration settings"
  _msg_info "       Install date:   ${install_date}"
  _msg_info "     Root directory:   ${root_dir}"
  _msg_info "     Tree directory:   ${tree_dir}"
  _msg_info "   Shared directory:   ${shared_dir}"
}

_globals
_global_variables

while \
  getopts \
    'cvh?' \
    arg; do
  case \
    "${arg}" in
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _usage \
	   1 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( "$#" < 3 )); then
  _set_overrides
  _usage \
    1
fi
root_dir="${1}"
tree_dir="${2}"
shared_dir="${3}"
_set_overrides
app_opts=(
  "${root_dir}"
  "${tree_dir}"
  "${shared_dir}"
)
_termux_install_shared \
  "${app_opts[@]}"
