#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="$(
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"

_requirements() {
  _check_cmd \
    "tar"
}

_global_variables() {
  get_date=""
  target_recipe=""
  target_variable=""
  cache_dir=""
  color=""
  quiet=""
}

# Reads a variable from the PKGBUILD
_version_split() {
  local \
    _string="${1}" \
    _variable="${2}" \
    _cache_dir="${3}" \
    _resolve_flag \
    _return \
    _sep \
    _separators=()
  _resolve_flag="false"
  _return=""
  _separators=(
    "<="
    ">="
    "<"
    ">"
    "="
  )
  _return="${_string}"
  for _sep in "${_separators[@]}"; do
    if [[ "${_string}" == *"${_sep}"* ]]; then
      _name="${_string%${_sep}*}"
      _pkgver="${_string#${_name}${_sep}}"
      _resolve_flag="true"
      if [[ "${_variable}" == "name" ]]; then
        _return="${_name}"
      elif [[ "${_variable}" == "version" ]]; then
        _return="${_pkgver}"
      else
        _msg=(
          "Unknown variable name"
          "'${_variable}'."
        )
        _msg_error \
          "${_msg[*]}" \
          1
      fi
      break
    fi
  done
  if [[ "${_return}" == "" ]]; then
    return 1
  elif [[ "${_resolve_flag}" == "true" || \
	  "${_return}" != "" ]]; then
    echo \
      "${_return}"
    return \
      0
  fi
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  IFS='' \
    read \
      -r \
      -d '' \
      usage_text << \
        ENDUSAGETEXT || true

Extract package name or version from a depend string.

usage:

  ${app_name}
    [options]
    <string> 
    <variable>

  variable args:
    name                  Extract the package name.
    version               Extract the package version.

  options:
     -h                   This message.
     -c                   Enable colors
     -v                   Enable verbose output
ENDUSAGETEXT
  printf \
    '%s\n' \
    "${usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      ${1}
    )
  for _flag \
    in "${_flags[@]}"; do
  _msg_info "                              ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration settings"
  _msg_info "                 Get date:   ${get_date}"
  _msg_info "                   String:   ${target_string}"
  _msg_info "                 Variable:   ${target_variable}"
}

_requirements
_globals
_global_variables

while \
  getopts \
    'cvh?' \
    arg; do
  case \
    "${arg}" in
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _usage \
	   1 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'." \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( "${#}" < 1 )); then
  _set_overrides
  _usage \
    1
fi
target_string="${1}"
if (( "${#}" < 2 )); then
  target_variable="name"
fi
if (( 1 < "${#}" )); then
  target_variable="${2}"
fi
_set_overrides
_show_config
app_opts=(
  "${target_string}"
  "${target_variable}"
  "${cache_dir}"
)
_version_split \
  "${app_opts[@]}" \
  "${args[@]}"
